export const authCopy = {
  appName: "KaarYab Afghanistan",
  loginTitle: "Welcome back",
  loginButtonLabel: "Login",
  loginSubmitLabel: "Login",
  signupTitle: "Create account",
  signupButtonLabel: "Sign up",
  signupSubmitLabel: "Create account",
  emailLabel: "Email",
  passwordLabel: "Password",
  fullNameLabel: "Full name",
  confirmPasswordLabel: "Confirm password",
  emailPlaceholder: "satayesh@example.com",
  passwordPlaceholder: "Enter your password",
  fullNamePlaceholder: "Your full name",
  confirmPasswordPlaceholder: "Re-enter your password",
  submitLabel: "Continue",
  loadingText: "Loading...",
  welcomeLabel: "KaarYab Afghanistan",
  signOutLabel: "Sign out",
  guestLabel: "Guest",
};
