export const authCopy = {
  appName: "KaarYab Afghanistan",
  loginTitle: "Welcome back",
  loginSubtitle: "Sign in to continue your search, save opportunities, and manage your profile.",
  loginButtonLabel: "Login",
  loginSubmitLabel: "Login",
  loginSuccessTitle: "Signed in successfully",
  loginSuccessMessage: "Your dashboard is ready. We have opened your account.",
  loginHint: "Use your registered email to access saved jobs and profile details.",
  signupTitle: "Create account",
  signupSubtitle: "Set up your profile once and start applying faster.",
  signupButtonLabel: "Sign up",
  signupSubmitLabel: "Create account",
  signupSuccessTitle: "Account ready",
  signupSuccessMessage: "Your account has been created. Finish your profile to start applying.",
  signupPendingTitle: "Check your inbox",
  signupPendingMessage: "We sent a confirmation link to your email address.",
  signupHint: "It only takes a minute to create your free KaarYab account.",
  emailLabel: "Email",
  passwordLabel: "Password",
  fullNameLabel: "Full name",
  confirmPasswordLabel: "Confirm password",
  emailPlaceholder: "satayesh@example.com",
  passwordPlaceholder: "Enter your password",
  fullNamePlaceholder: "Your full name",
  confirmPasswordPlaceholder: "Re-enter your password",
  submitLabel: "Continue",
  loadingText: "Loading...",
  welcomeLabel: "KaarYab Afghanistan",
  signOutLabel: "Sign out",
  guestLabel: "Guest",
  authErrorFallback: "Something went wrong. Please try again.",
  loginErrorFallback: "We could not sign you in. Check your credentials and try again.",
  signupErrorFallback: "We could not create your account. Please review the form and try again.",
};
